server:
  port: 9000
  servlet:
    session:
      cookie:
        name: JSESSIONID
        max-age: 2592000
        domain: 127.0.0.1
        secure: false
        http-only: false
spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usercenter2
    username: root
    password: 123456
  cors:
    allowed-origins: "http://localhost:8080"  # 允许来自这个地址的请求
    allowed-methods: "*"  # 允许的HTTP方法，"*"表示允许所有方法
    allowed-headers: "*"  # 允许的头部信息，"*"表示允许所有头部
    allow-credentials: true  # 是否允许发送凭据，例如cookies

  ##驼峰命名法
  #mybatis:
  #  configuration:
  #    map-underscore-to-camel-case: true
  #一天过期
  session:
    timeout: 86400


